name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Host
      run: |
        export DEPLOYPATH=/home/appedirn/public_html/gym-backend
        /bin/cp -R images $DEPLOYPATH
